export const BEAT_CONSTANTS = {
  GET_BEATS_REQUEST: 'GET_BEATS_REQUEST',
  GET_BEATS_SUCCESS: 'GET_BEATS_SUCCESS',
  GET_BEATS_FAILURE: 'GET_BEATS_FAILURE',

  GET_BEAT_BY_ID_REQUEST: 'GET_BEAT_BY_ID_REQUEST',
  GET_BEAT_BY_ID_SUCCESS: 'GET_BEAT_BY_ID_SUCCESS',
  GET_BEAT_BY_ID_FAILURE: 'GET_BEAT_BY_ID_FAILURE',

  CREATE_BEAT_REQUEST: 'CREATE_BEAT_REQUEST',
  CREATE_BEAT_SUCCESS: 'CREATE_BEAT_SUCCESS',
  CREATE_BEAT_FAILURE: 'CREATE_BEAT_FAILURE',

  DELETE_BEAT_REQUEST: 'DELETE_BEAT_REQUEST',
  DELETE_BEAT_SUCCESS: 'DELETE_BEAT_SUCCESS',
  DELETE_BEAT_FAILURE: 'DELETE_BEAT_FAILURE',

  UPDATE_BEAT_REQUEST: 'UPDATE_BEAT_REQUEST',
  UPDATE_BEAT_SUCCESS: 'UPDATE_BEAT_SUCCESS',
  UPDATE_BEAT_FAILURE: 'UPDATE_BEAT_FAILURE',

  PLAY_BEAT_REQUEST: 'PLAY_BEAT_REQUEST',
  PLAY_BEAT_SUCCESS: 'PLAY_BEAT_SUCCESS',
  PLAY_BEAT_FAILURE: 'PLAY_BEAT_FAILURE',
};
